### ISSUE TITLE
No open file dialog

### ISSUE THREAD

**Issue by Ygarr** [marchellodev/sharik#78] opened 2021-07-01 00:47 UTC
(sharik:102056): Gtk-WARNING **: 03:44:54.081: drawing failure for widget 'GtkBox': error occurred in libfreetype
package: linux zip
OS: Manjaro

No file system in open file dialog

**Comment by marchellodev** [comment] 2021-07-01 10:40
What packaging did you use?

**Comment by marchellodev** [comment] 2021-07-01 10:58
Seems to be a duplicate of #62

**Closed by marchellodev** 2021-07-01 10:58 UTC
