### ISSUE TITLE
Feature request: Receiving shared data by other applications

### ISSUE THREAD

**Issue by zerofancy** [marchellodev/sharik#43] opened 2021-02-16 05:05 UTC
I like this app very much, thanks for developing it. 

I think it would be better if Sharik can receive data shared by other apps, like this: 

[Receiving shared data in Flutter using Android Send Intents and iOS Share Extensions](https://levelup.gitconnected.com/receiving-shared-data-in-flutter-using-android-send-intents-and-ios-share-extensions-b6a2a3fdf998)

Best regards.

**Comment by marchellodev** [comment] 2021-02-16 05:44
An amazing idea! Thanks!

**Comment by marchellodev** [comment] 2021-06-16 14:43
Duplicate of #59

This is implemented in Sharik v3 https://github.com/marchellodev/sharik/issues/63 !

Thank you for the suggestion, I'll close this issue for now.

**Closed by marchellodev** 2021-06-16 14:43 UTC
Labels: enhancement
