### ISSUE TITLE
Select multiple files at once

### ISSUE THREAD

**Issue by Hx2-code** [marchellodev/sharik#40] opened 2021-02-11 14:46 UTC
Ability to select multiple files in file selector will help share multiple files at once without requiring to select individual file one by one.

**Comment by marchellodev** [comment] 2021-02-11 16:04
Duplicate of #5.

Thanks for the issue btw!

**Closed by marchellodev** 2021-02-11 16:04 UTC
Labels: duplicate

**Comment by Hx2-code** [comment] 2021-02-13 04:40
Sorry about that
